version: '3.3'

services:
  web:
    build: .
#    container_name: blog
    ports:
      - 8000:8000
    env_file:
      - ./.env
    volumes:
      - staticimages:/images
      - serverlog:/var/log
#      - sqlite:./db.sqlite3

volumes:
#  sqlite:
  staticimages:
  serverlog:
